name: Deploy on Render

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove node_modules and package-lock.json
      run: rm -rf node_modules package-lock.json 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to deploy-onrender Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Checkout the current working branch (whatever triggered the workflow)
        CURRENT_BRANCH=$(git branch --show-current)
        
        # Switch to the deploy-onrender branch (create it if it doesn't exist)
        if git rev-parse --verify origin/deploy-onrender; then
          git checkout deploy-onrender
          git reset --hard origin/$CURRENT_BRANCH
        else
          git checkout -b deploy-onrender
        fi

        # Add and commit everything from the working branch
        git add --all
        git commit -m "Deploying latest changes from $CURRENT_BRANCH to deploy-onrender"
        git push --force origin deploy-onrender